---
title: "Reviewing"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(pander)
library(DT)
library(car)
library(readr)

view(starwars)
?starwars
```



```{r cars}
pander(table(starwars$species))
starwars.human2 <- filter(starwars, species %in% c("Human", "Wookiee"))
pander(t.test(height ~ species, data = starwars.human, mu = 0, alternative = "two.sided", conf.level = 0.95))
qqPlot(starwars.human2$species)
```

```{r}
pander(table(starwars$homeworld))
starwars.human <- filter(starwars, species == "Human")
pander(wilcox.test(height ~ gender, data = starwars.human, mu = 0, alternative = "two.sided", conf.level = 0.95))
```


```{r}
starwars.aov2 <- aov(height ~ as.factor(gender), data = starwars)
pander(summary(starwars.aov2))
```

```{r}
starwars.aov <- aov(height ~ as.factor(gender) + as.factor(species) + as.factor(gender):as.factor(species), data = starwars)
pander(summary(starwars.aov))

```

```{r}
pander(kruskal.test(height ~ species, data = starwars))
```

